# Generated by Django 5.0 on 2023-12-10 19:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_num', models.SmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(unique=True)),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=8)),
                ('types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=4)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=70)),
                ('base_stats', models.JSONField()),
            ],
            options={
                'verbose_name': 'pokedex',
                'verbose_name_plural': 'pokedexes',
                'db_table': 'pokedex',
            },
        ),
    ]
