# Generated by Django 5.0 on 2023-12-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='description',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
