# Generated by Django 5.0 on 2023-12-15 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokedex_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='pokedex_num',
            field=models.SmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
