# Generated by Django 5.0 on 2023-12-15 18:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_alter_pokedex_abilities_alter_pokedex_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokedex',
            name='abilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=8),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=70),
        ),
        migrations.AlterField(
            model_name='pokedex',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Normal', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Grass', 'Grass'), ('Electric', 'Electric'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel')], max_length=8), size=2),
        ),
    ]
